version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_API_KEY=${WEBHOOK_API_KEY}
      - OAUTH_SERVER_URL=${OAUTH_SERVER_URL:-https://api.manus.im}
      - VITE_OAUTH_PORTAL_URL=${VITE_OAUTH_PORTAL_URL:-https://login.manus.im}
      - VITE_APP_ID=${VITE_APP_ID}
      - VITE_APP_TITLE=${VITE_APP_TITLE:-Leverage Therapy}
      - VITE_APP_LOGO=${VITE_APP_LOGO:-/logo.png}
      - OWNER_OPEN_ID=${OWNER_OPEN_ID}
      - OWNER_NAME=${OWNER_NAME}
      - BUILT_IN_FORGE_API_URL=${BUILT_IN_FORGE_API_URL}
      - BUILT_IN_FORGE_API_KEY=${BUILT_IN_FORGE_API_KEY}
      - VITE_ANALYTICS_ENDPOINT=${VITE_ANALYTICS_ENDPOINT}
      - VITE_ANALYTICS_WEBSITE_ID=${VITE_ANALYTICS_WEBSITE_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add MySQL if you don't have an external database
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=therapyconnect
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
